### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by sajumani** [zmts/supra-api-nodejs#15]
Hi Team,

All the endpoints accessible without access token,

Is it Normal ?

**Comment by sajumani** [comment]
Some body can you help me with this ?

We stuck up here, while we moving to production

**Comment by zmts** [comment]
@sajumani If you don't use access token that means user role is `ROLE_ANONYMOUS`. To adjust anonymous user permissions jump to https://github.com/zmts/supra-api-nodejs/blob/master/permissions/RoleAnonymousAccess.js

Also you can use some policy. Related on your terms.
https://github.com/zmts/supra-api-nodejs/tree/master/policy

Example
https://github.com/zmts/supra-api-nodejs/blob/master/modules/posts/actions/UpdatePostAction.js#L30

**Comment by sajumani** [comment]
Thanks it works well!

**Comment by sajumani** [comment]
'users:list': true,
      'users:update': true,
      'users:get-by-id': true,
      'users:remove': true,

this not like real route , Where do we config this ?
