### ISSUE TITLE
Supra with MongoDB

### ISSUE THREAD

**Issue by sajumani** [zmts/supra-api-nodejs#16]
Hi Team,

Again thanks for wonderful Support.

We have one more issue; Is it possible to use Supra with NoSQL Data Base such as MongoDB.

It's working good with MySQL, MSSQL, Postgresql

**Comment by sajumani** [comment]
@zmts Any idea ?

Supra with MongoDB

**Comment by zmts** [comment]
Yes it can be done with updating DAO layer. Up to you.

**Comment by zmts** [comment]
Nope

**Comment by sajumani** [comment]
Otherwise let me move to loopback

**Comment by sajumani** [comment]
@zmts In future, Shall we expect MongoDB support ?

**Comment by zmts** [comment]
@sajumani Supra-API its just some kind of architecture pattern, not a high level framework like loopback where you can switch DB by changing some key. So any data layer modifications should to be done from engineer end. PostgreSQL used as example for my needs, you can do the same with Mongo for you needs :) MongoDB is not planned its not relevant for me, for now.

**Comment by sajumani** [comment]
@zmts   Supra-API its just some kind of architecture pattern   That i understood...

And i liked architecture you used here... with knex  i used to connect all Sql DataBases. it working wonderful

But i would not connect to NoSql Databases.  Since kenx not supporting

Thats why asked any possible way to do noSql databases ?

**Comment by zmts** [comment]
@sajumani of course you can.
Just remove knex initialization (https://github.com/zmts/supra-api-nodejs/blob/master/main.js#L41) and add new one for mongo, respectively with data layer upgrading.
