### ISSUE TITLE
What does it take to do something like this?

### ISSUE THREAD

**Issue by ilbrigz** [zmts/supra-api-nodejs#3]
Though I don't understand 90% of your code :D, but by just looking at it's structure and dependancies, I'm sure that it's well beyond my skills. I can't even comprehend most of the codes. 

Just discouraging. Maybe, comfort this noob? :D 

Soo, What does it take to do something like this? I don't see myself doing something like this in the next 1 to 2 years plus my previous 2 years self-study. Udemy courses don't even teach these kind of complexity. Where do I start? How can I break this down and start understanding its parts?

**Comment by zmts** [comment]
@ilbrigz Hi! It's ok if you can't understand at once time. You can check something easier like https://github.com/zmts/skeleton-api-nodejs. For basics try to learn course from Wes Bos https://wesbos.com/learn-node/ it's a pretty nice course. Just do it step by step. Good luck
