### ISSUE TITLE
Access Denied during Logout

### ISSUE THREAD

**Issue by Leeibrah** [zmts/supra-api-nodejs#5]
Hello,

I am getting the error: "message": "Access denied, don't have permissions." when trying to logout. 

I have my added the "refreshToken": "my_refresh_token" under the JSON application body and I  don't understand why I am getting the above error message. Let me know what I am missing or what I am doing wrong on my postman.

Thanks.

**Comment by zmts** [comment]
Hi! You forget access token in `authorization` header

**Comment by zmts** [comment]
`/auth/logout` requires authorization
https://github.com/zmts/supra-api-nodejs/blob/master/permissions/BaseRoleAccess.js

**Comment by Leeibrah** [comment]
It worked perfectly with the Bearer Token. Thanks.
